"""Adding node id to all the other objects

Revision ID: 12b25e7a833d
Revises: fa72c8637e4f
Create Date: 2024-07-14 01:06:33.508114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b25e7a833d'
down_revision = 'fa72c8637e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_events_node_id', 'nodes', ['node_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_locations_node_id', 'nodes', ['node_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notes_node_id', 'nodes', ['node_id'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_people_node_id', 'nodes', ['node_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('node_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('node_id')

    # ### end Alembic commands ###
