"""Added text start and end points for the Note table to enable text highlighting

Revision ID: 7818dd9089ac
Revises: 12b25e7a833d
Create Date: 2025-02-11 22:52:13.315915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7818dd9089ac'
down_revision = '12b25e7a833d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('text_end', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('text_end')
        batch_op.drop_column('text_start')

    # ### end Alembic commands ###
